openapi: 3.0.3
info:
  title: -APP- API docs
  version: 1.0.0-alpha-1
  description: This is the API documentation for the server-side app -APP-

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Mobile
    description: User management operations

paths: {}

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
