openapi: 3.0.3
info:
  title: Shorten URL API docs
  version: 1.0.0-alpha-1
  description: This is the API documentation for the server-side app Shorten URL

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Auth
    description: Auth collection
  - name: Url
    description: Url collection

paths: {}

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
